//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trvel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int FlightID { get; set; }
        public string Type { get; set; }
        public string FromCity { get; set; }
        public string ToCity { get; set; }
        public string Class { get; set; }
        public int Childrens { get; set; }
        public int Adults { get; set; }
        public string DepartDate { get; set; }
        public string ReturnDate { get; set; }
    }
}
